require("hyprland.execs")
require("hyprland.config")
require("hyprland.rules")
require("hyprland.curves")
require("hyprland.animations")
require("hyprland.monitors")
require("hyprland.gestures")
require("hyprland.keybinds")

require("noctalia")
