return {
    MODIFIER = {
        SUPER = "SUPER",
        CTRL = "CONTROL",
        ALT = "ALT",
        SHIFT = "SHIFT"
    },
    ALPHABET = {
        A = "A",
        B = "B",
        C = "C",
        D = "D",
        E = "E",
        F = "F",
        G = "G",
        H = "H",
        I = "I",
        J = "J",
        K = "K",
        L = "L",
        M = "M",
        N = "N",
        O = "O",
        P = "P",
        Q = "Q",
        R = "R",
        S = "S",
        T = "T",
        U = "U",
        V = "V",
        W = "W",
        X = "X",
        Y = "Y",
        Z = "Z"
    },
    ARROW = {
        LEFT = "LEFT",
        RIGHT = "RIGHT",
        UP = "UP",
        DOWN = "DOWN",
    },
    PUNCTUATION = {
        COMMA = "COMMA",
        PERIOD = "PERIOD",
        SEMICOLON = "SEMICOLON",
        APOSTROPHE = "APOSTROPHE",
    },
    SYMBOL = {
        EQUAL = "EQUAL",
        MINUS = "MINUS",
        BRACKETRIGHT = "BRACKETRIGHT",
        BRACKETLEFT = "BRACKETLEFT",
        SLASH = "SLASH",
        BACKSLASH = "BACKSLASH",
        BACKTICK = "GRAVE"
    },
    SPECIAL = {
        BACKSPACE  = "BACKSPACE",
        ENTER = "RETURN",
        SPACE = "SPACE",
        TAB = "TAB",
        ESCAPE = "ESCAPE",
        PRINT = "PRINT"
    },
    LOCKS = {
        CAPSLOCK = "Caps_Lock",
        NUMLOCK = "Num_Lock",
        SCROLLLOCK = "Scroll_Lock"
    },
    NAVIGATION = {
        INSERT = "INSERT",
        DELETE = "DELETE",
        HOME = "HOME",
        END = "END",
        PGUP = "PRIOR",
        PGDN = "NEXT",
    },
    FUNCTION = {
        F1 = "F1",
        F2 = "F2",
        F3 = "F3",
        F4 = "F4",
        F5 = "F5",
        F6 = "F6",
        F7 = "F7",
        F8 = "F8",
        F9 = "F9",
        F10 = "F10",
        F11 = "F11",
        F12 = "F12",
    },
    XF86 = {
        HOMEPAGE = "XF86HomePage",                             
        MAIL = "XF86Mail",                                     
        SEARCH = "XF86Search",                                 
        TOOLS = "XF86Tools",                                   
        AUDIOPLAY = "XF86AudioPlay",                           
        AUDIOPREV = "XF86AudioPrev",                           
        AUDIONEXT = "XF86AudioNext",                           
        AUDIOLOWERVOLUME = "XF86AudioLowerVolume",             
        AUDIORAISEVOLUME = "XF86AudioRaiseVolume",             
        AUDIOMUTE = "XF86AudioMute",                           
        EXPLORER = "XF86Explorer",                             
        CALCULATOR = "XF86Calculator",                         
        BRIGHTNESSDOWN = "XF86MonBrightnessDown",              
        BRIGHTNESSUP = "XF86MonBrightnessUp",                  
        SLEEP = "XF86Sleep",                                   
    },
    MOUSE = {
        LMB = "mouse:272",
        RMB = "mouse:273",
        MMB = "mouse:274"
    }, 
}
